// Temporary stub generated by template. Run `pnpm --filter @template/convex convex codegen`
// to replace with real generated code.

// Loosened types so the template typecheck passes without real codegen.
export type QueryCtx = { db: any };
export type MutationCtx = { db: any };
export type ActionCtx = unknown;

export const query = <Args, Result>(def: {
  args: Args;
  handler: (ctx: QueryCtx, args: Args) => Promise<Result> | Result;
}) => def;

export const mutation = <Args, Result>(def: {
  args: Args;
  handler: (ctx: MutationCtx, args: Args) => Promise<Result> | Result;
}) => def;

export const action = <Args, Result>(def: {
  args: Args;
  handler: (ctx: ActionCtx, args: Args) => Promise<Result> | Result;
}) => def;
